    - name: Compile and Archive App
      run: |
        xcodebuild archive \
          -workspace . \
          -scheme MyApp \
          -destination "generic/platform=iOS" \
          -archivePath ./build/MyApp.xcarchive \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO

    - name: Package Into IPA File
      run: |
        xcodebuild -exportArchive \
          -archivePath ./build/MyApp.xcarchive \
          -exportPath ./build/output \
          -exportOptionsPlist ExportOptions.plist \
          -destination "generic/platform=iOS" \
          CODE_SIGNING_ALLOWED=NO
